import Head from "next/head";
import react from "react";
import Map from "react-map-gl";
import MenuBar from "../components/parts/MenuBar";
import TopMap from "../components/elements/TopMap";
import Coupon from "./assets/Coupon";

export default function Home() {
  return (
    <div className="h-full overflow-hidden">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
      </Head>

      <MenuBar />

      <TopMap />
    </div>
  );
}
